apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque   # Opaque type is used for storing arbitrary user-defined data
# This Secret is used to store the MySQL database password securely.
data:
  db-password: cm9vdHBhc3N3b3Jk # Base64 encoded value of 'rootpassword'
  # Note: The value 'cm9vdHBhc3N3b3Jk' is the Base64 encoding of 'rootpassword'.
  # You can encode your own password using the command:
  # echo -n 'yourpassword' | base64
