apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: jeeventus
  labels:
    app: mysql  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.7
          args: ["--ignore-db-dir=lost+found"]  # This prevents initialization errors
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password
            - name: MYSQL_DATABASE
              value: usermgmt
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          # Add these lifecycle hooks to ensure proper startup
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chown -R mysql:mysql /var/lib/mysql"]
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-mysql-pv-claim