apiVersion: v1
kind: Service  
metadata:
  name: mysql-clusterip-service # Name of the service
  namespace: jeeventus
spec: 
  type: ClusterIP # This service type is used for internal communication within the cluster
  selector:
    app: mysql # This should match the labels defined in the MySQL deployment
  ports:
    - port: 3306 # The port that the service will expose
      targetPort: mysql-port # This should match the name of the port defined in the MySQL deployment
      protocol: TCP # Protocol used by the service
  sessionAffinity: None # No session affinity for this service
  clusterIP: None # This allows for a headless service, which is useful for stateful applications like MySQL (This means we are going to use POD IPs directly)