apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-microservice
  labels:
    app: user-management-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-restapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-management-restapp
    spec:
      restartPolicy: Always
      containers:
        - name: user-management-restapp
          image:  stacksimplify/kube-usermanagement-microservice:1.0.0 # Replace with your actual image name
          ports:
            - containerPort: 8095 # Replace with the port your application listens on 
          env:
            - name: DB_HOSTNAME
              value:   "mysql-clusterip-service" # This should match the name of the MySQL service
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              value: "rootpassword" # Ensure this matches the MySQL root password