apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      server: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        server: nginx
    spec:
      initContainers:
      - name : my-init
        image: hello-world
      containers:
      - name: my-nginx-container
        image: nginx:1.21.6
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
