apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      server: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
      - name: my-nginx-container
        image: nginx:1.21.6
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: server
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 3600; done"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
