apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myPod
    type: proxy
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"

    # Exposing port 80 for HTTP traffic as this container serves a web application.
    ports:
      - containerPort: 80


