apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
  namespace: jeeventus
type: Opaque   # Opaque type is used for storing arbitrary user-defined data
# This Secret is used to store the MySQL database password securely.
data:
  db-password: ZGJwYXNzd29yZDEx # Base64 encoded value of 'dbpassword11'
  # Note: The value 'ZGJwYXNzd29yZDEx' is the Base64 encoding of 'dbpassword11'.
  # You can encode your own password using the command:
  # echo -n 'yourpassword' | base64
