apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv01
spec:
  capacity:
    storage:  2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: admstor
  hostPath:
    path: /data/pv01
 