apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: pvcdemoapp  
spec:
  containers:
  - name: pvcdemoapp-container
    image: nginx:1.21.6
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"

    # Exposing port 80 for HTTP traffic as this container serves a web application.
    ports:
      - containerPort: 80
    
    volumeMounts:
      - name: pvstor
        mountPath: /usr/share/nginx/html


  volumes:
    - name: pvstor 
      persistentVolumeClaim:
        claimName: mypvc01
      
